"""Dataset / interchange schemas for the P3 data layer (T3.2).

Defines the provenance :class:`SourceTag` enum and the two frozen interchange
records: :class:`TransitionDTO` (a single agent-step dataset record) and
:class:`DatasetManifest` (provenance for a saved BC/replay artifact). These are
PURE data carriers — no business logic, no config reads. The replay buffer
(:mod:`src.marl.replay`) stores padded WHOLE EPISODES (different shapes) and is
deliberately NOT conflated with the single-step ``TransitionDTO``.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum

import numpy as np


class SourceTag(StrEnum):
    """Provenance label for a stored transition/episode (string-valued).

    A StrEnum so the member serializes directly into npz/JSON artifacts and the
    replay buffer's per-item tag column without an extra ``.value`` lookup.

    Attributes:
        EXPERT: Generated by a Manhattan-heuristic oracle (BC labels).
        SELF_PLAY: Generated by a frozen-opponent self-play rollout.
        RANDOM: Generated by a uniform-random policy (exploration/baseline).
        LIVE_CTDE: Generated on-policy during centralized-training collection.
    """

    EXPERT = "expert"
    SELF_PLAY = "self_play"
    RANDOM = "random"
    LIVE_CTDE = "live_ctde"


@dataclass(frozen=True)
class TransitionDTO:
    """Immutable single agent-step dataset/interchange record.

    Attributes:
        obs: Local egocentric observation image ``(C, 5, 5)`` float32 for ONE
            agent (channels-first, matching the env ``Observation``).
        scalars: The ``(obs_scalars,)`` float32 aliasing-memory hooks.
        global_state: The stage-invariant ``(77,)`` float32 encoded global state
            (see :func:`src.marl.data.obs_encoder.encode_state`).
        action: The agent's chosen discrete action index.
        reward: The scalar step reward for this agent.
        done: Whether this step landed in a terminal (absorbing) state.
        next_legal_mask: The ``(a_cop,)`` boolean legality mask at the NEXT state
            (stored, never recomputed from cropped obs; PRD:486 for P4 Double-DQN).
    """

    obs: np.ndarray
    scalars: np.ndarray
    global_state: np.ndarray
    action: int
    reward: float
    done: bool
    next_legal_mask: np.ndarray


@dataclass(frozen=True)
class DatasetManifest:
    """Immutable provenance for a saved BC/replay artifact.

    Attributes:
        grid: The ``(h, w)`` board size the artifact was generated on.
        n_pairs: Number of (obs, action) records in the artifact.
        seed: The seed driving the (reproducible) generation.
        source: A :class:`SourceTag` value string for the artifact's provenance.
        obs_channels: Egocentric image channel count (``env.obs_channels``).
        obs_scalars: Aliasing-memory scalar count (``env.obs_scalars``).
        w_v: Egocentric window width ``2 * view_radius_max + 1``.
        schema_version: A contract-version string for forward compatibility.
    """

    grid: tuple[int, int]
    n_pairs: int
    seed: int
    source: str
    obs_channels: int
    obs_scalars: int
    w_v: int
    schema_version: str
